[package]
name = "erlpack"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1.4.3"
js-sys = "0.3.64"
num-bigint = "0.4.3"
wasm-bindgen = "0.2.87"
